LOAD DATA LOCAL INFILE '/masivo_clientes.csv'
INTO TABLE PRODUCTOS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(	ID_PRODUCTO,
    NOMBRE_PRODUCTO,
    PRECIO,
    FOTO_PRODUCTO);
    
LOAD DATA LOCAL INFILE '/masivo_roles.csv'
INTO TABLE ROLES
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(		ID_ROL,
    DESCRIPCION);
    
    
    
LOAD DATA LOCAL INFILE '/masivo_estados.csv'
INTO TABLE ROLES
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(	ID_ESTADOS,
    DESCRIPCION);
    
    
LOAD DATA LOCAL INFILE '/masivo_usuarios.csv'
INTO TABLE USUARIOS
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(	ID_USUARIO,
    USUARIO,
    CONTRASENA_USUARIO,
    NOMBRES,
    APELLIDOS,
    CORREO,
    DIRECCION,
    CELULAR,
    ID_ROL);
    
    LOAD DATA LOCAL INFILE '/masivo_ordenes.csv'
INTO TABLE ORDENES
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(	ID_ORDEN,
    ID_USUARIO,
    ID_ESTADOS,
    FECHA,
    DESCRIPCION,
    PRECIO_TOTAL
    );
    
LOAD DATA LOCAL INFILE '/masivo_ordenxproducto.csv'
INTO TABLE PRODUCTO_ORDENES
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
(	
	ID_PRODUCTO_ORDEN,
    ID_PRODUCTO,
    ID_ORDEN,
    CANTIDAD_PRODUCTO
    );